
spring:
  datasource:
#    password: L3e5F7u8
#    username: root
    password: yy3B5uYf5f34BjV89
    username: admin
#    url: jdbc:mysql://111.231.205.128:3306/music_fire?useSSL=false&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/music_fire?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
  redis:
    host: 127.0.0.1
    port: 6379
    keyPrefix: jeeplus
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    view:
      prefix: /pages/
      suffix: .html


#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.musicfire.modular.system.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1

init:
  appRole: false #初始化应用角色信息（角色中心）
  appInfo: false #初始化应用资源信息（应用中心）
  adminRole: false #初始化admin账号角色信息（角色中心）
server:
  port: 8081

mqtt:
  broker:
    serverUri: tcp://39.104.54.139:1883
    username: guest
    password: guest
  pclientId: vm-producer
  cclientId: vm-customer
  topics: state/#,register,offline
  qos: 1
  qos2: 0,1,2
  completionTimeout: 5000


wechat:
  mpAppId: wx38031f18f6f7ac55
  mpAppSecret: bf07cc1ae51b464aab90ade6a44c7a59
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1502968311
  mchKey: 8dd841e0b6d54fa08d7426e0d61b4c8a
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl:  http://1c592r8399.51mypc.cn/wxpay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://1c592r8399.51mypc.cn
  wechatOpenAuthorize: http://1c592r8399.51mypc.cn
  vendingmachine: http://1c592r8399.51mypc.cn
  mobile: http://1c592r8399.51mypc.cn/mobile


# 支付宝网关名、partnerId和appId
alipay:
  open_api_domain: https://openapi.alipay.com/gateway.do
  mcloud_api_domain: http://mcloudmonitor.com/gateway.do
  uid: 2088102175761651
  appid: 2018051960121986
  return_url:  http://1c592r8399.51mypc.cn/alipay/return
  notify_url:  http://1c592r8399.51mypc.cn/alipay/notify

  # RSA私钥、公钥和支付宝公钥
  private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCH6xXA5OT92VFJ
    nYKNqlP5SLDoVw5sIGkjt8BdCEm3hGLD5fIlJ0rLpDOBARed5blSJXVDM7ldtNpm
    W7OtwHa4gZAIePuOQnd0iSxrCWv80HzI69nwxZgs77xlD+0KiqLXVgrb/Wyyiziu
    rXRBIF8s+KsGnBAy1iMfo6fCXDLpWsULOu4aZtpZjyuiO6bEC65qza0lVq2s5qRI
    Gqb14S1ZABC2cNqyDa7mGNvC67SW0YLcJYiLjTwxNwjvpD/kmk7BExZ856T6pC5E
    gtiKOLD/rQ2cLyuqE23XrTXG/wgRJfIbl2+xv7GkY8sKTaULBv5m5hZDX0qmBqib
    +CPMWQwzAgMBAAECggEBAIBL8Z7A8T6E8ewRF/jtPJLkgMjv1BdQiK5EdvnaJutp
    tWjBF07mxf1vo4Y0J7zN6Z6W6RdkLac8XaOdEAAE2ovTEMhOmvVv3B5OlXT70ck0
    a3Wk23YgrkJMkYK8A76dmpS1DU8W6pGmRPztkf0ft3dVyupUSh4Sb9kfu+0E5rHJ
    sfWvHjGYFR/Rvdfld3hcYWQgdJJNn+yWHAuNTh8DfCXqqd3+ZBwahuEF3eSL4Of5
    SyviWcEkSk5oAHX1tUnuHFHlo6kwEETKnEpDIGnOAt2LfpvjjxUo0q92HcEv350Y
    Ldkm0zdsrc6O88dMg3rfDwAR4i7F55+8ygisa0cSwTECgYEAxEKfFro89DPf341e
    otnhjhBURpyNwqjieRrAdU/Gw6fOHulgS3DXopQEDtupBsXbeHKjx8KBXAhyLsfj
    B8igXmRvZg7gri1YbKaaKlwIxho5j9Oe5J4OdIRwLkw6l090bozvbr5kugXPjKKV
    k43LLVAas753YEYrUiZFWFTnCc8CgYEAsUphLZa+9r3xlcCDIqEkSMHSxoFcKf+2
    XfiqubrBMAHtyd9fB02ZMCbCUCqugd5knBtFbWCDoWEUtVmUGVBgkxgX/gB7E7/i
    ZoOROE+lso1DgO5ac5aI/AnlqnaIBM+IVaAiJ6Rjyw3BBKaaQNESfidrFB8fD2Ns
    GCxTU2KYxF0CgYBxAALlbRnHaU7PQnBox5aM224Ksf0VRXQQUozZfrNs1+Nf/PNK
    vJALtbmYbHUnxygUc71FOQKOYPaNZN2dD7D2aFGTq6FF6CnvdQVyukb6+QKHg0sL
    Ss373H1SyuU5VbAuLst1Mf6A9POJf9sreAqx7ltRfqrxLbWnuQ1YTJoyFQKBgQCK
    kjBSibjI8r2Y5teYgYrys0wji4iV6yCHYo1OjgHhnCBX4RdNhgFt+V13e2TabREG
    Uup5Cy7XPCILfPCcuI5DalmWVpncXeZ/aeZftSE15eQVKjfYkJiRJssz6WF3IR7W
    jksj4QF+/EkZcX6vmrpxkC3JlGmahYM/gaW/TxlIoQKBgQCtxcQk4C9aY3oWx8tT
    0u1ACILK0y3MBH8d8xvi+Z7CpgHwkQVGuTmcGzNvSjdJdWvSHq620DuYjRLBzgrj
    3ktIsR/26+Ig9B1UfCJfAQ/rvXvGe9ONIBf7YxmisTk1SvJgiFM41dgJm8id3AQm
    IX3cl99nmcROpMgYJ8GCYxVU2w==
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAh+sVwOTk/dlRSZ2CjapT+Uiw6FcObCBpI7fAXQhJt4Riw+XyJSdKy6QzgQEXneW5UiV1QzO5XbTaZluzrcB2uIGQCHj7jkJ3dIksawlr/NB8yOvZ8MWYLO+8ZQ/tCoqi11YK2/1ssos4rq10QSBfLPirBpwQMtYjH6Onwlwy6VrFCzruGmbaWY8rojumxAuuas2tJVatrOakSBqm9eEtWQAQtnDasg2u5hjbwuu0ltGC3CWIi408MTcI76Q/5JpOwRMWfOek+qQuRILYijiw/60NnC8rqhNt1601xv8IESXyG5dvsb+xpGPLCk2lCwb+ZuYWQ19Kpgaom/gjzFkMMwIDAQAB
  #SHA256withRsa对应支付宝公钥
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoH7HORKWUoEyU75/WUcf5i15mzwlqfQVlRQ8A5eCpo2mFZbRNyTyhkPX1nU3uKYQfigYwdT70+teJuQ9Ofd1GX/Dvy+9sX7DzIOd5oTFpr3PDnadTNqmbycJVYEZ0U8tWZKTarjSHPS5YqHzeYkKjaUm7IZuxQbj7yzis0Mo7RxHKfjYopolRZTWdviIR8+8RCZlrcutCNWhSokeBcNua4MWs16p0eFRYIcZcf1jC3u2F29Iv+lDx9fv9ZjoPS2B2xxNGz+RWy4Y7CMefwJM3skF1PFdyDa3sOTA+Qr2ceo1qvr2jCnwie2dST0c9U+PFRsZffShs78d0aFLora0vQIDAQAB
  # 签名类型: RSA->SHA1withRsa,RSA2->SHA256withRsa
  sign_type: RSA2

  AES: bjzht4GO40L0zoZOngGQmA==

  CHARSET: utf-8


path:
  base:
    win:  E:/server_file/vmc
    linux:  /opt/server_file/vmc

  relevant:
    shop: /upload/vmc/item/shop/
    headline: /upload/vmc/item/headtitle/
    shopcategory: /upload/vmc/item/shopcategory/
shoplog:
  onoff: true
